### ISSUE TITLE
fcgen references el2124 input file?

### ISSUE THREAD

**Issue by mcevoyandy** [nasa-jpl/fastcat#102]
In the README an example input file is referenced:

https://github.com/nasa-jpl/fastcat/blob/37080b7bf97b8f5043b276c1038fddf4a4fbf71a/src/fcgen/README.md?plain=1#L14

Is this the file that is meant? I don't see any other yaml files that reference el2124

`fastcat/example_configs/single/el2124_offline_config.yaml`

**Comment by alex-brinkman** [comment]
Start here to craft your YAML files and read what each control parameter means:
https://github.com/nasa-jpl/fastcat/blob/master/doc/fastcat_device_config_parameters.md

You can also see the instantiation of each device type in this example YAML file:
https://github.com/nasa-jpl/fastcat/blob/master/example_configs/one_of_every_device_offline.yaml

**Comment by alex-brinkman** [comment]
Oh sorry, mostly only developers interface with `fcgen` so I thought you were looking for YAML definitions.

This is the definition of the state channels for the EL2124:

https://github.com/nasa-jpl/fastcat/blob/37080b7bf97b8f5043b276c1038fddf4a4fbf71a/src/fcgen/fastcat_types.yaml#L306

**Comment by mcevoyandy** [comment]
No, the readme suggest that this tool is useful for devices that aren't already in the device list... what does the referenced input yaml look like? Is this the ESI file?

**Comment by alex-brinkman** [comment]
The generator referenced in this README is deprecated. It was an idea to streamline the addition of new devices, but I didn't want to maintain it and early device developers didn't use it either. 

There is an overhaul to `fcgen` in progress (#96) so I'll make sure to update all documentation associated with the README to make sure it's all up to date. I'll also be auto-coding documentation from this YAML too so integrators don't need to know anything about this input `fastcat_types.yaml` or how fcgen works under the hood - The idea is that all relevant info will be added to the `doc` markdowns and be readily digestible for humans.
