### ISSUE TITLE
Actuator not being able to reach up to max speed

### ISSUE THREAD

**Issue by davidinkyu-kim** [nasa-jpl/fastcat#14]
On a motor controller level(e.g. using Elmo Application Studio), the actuator spins at its tuned max speed.
Over fastcat configuration, CSP/CSV and ProfPos,ProfVel commands only reach up to some portion of speed.

**Comment by davidinkyu-kim** [comment]
On MAN-G-DS402, Object 0x6080 Max motor speed, is the max speed of the motor in RPM.
Previously implementation was in counts per second.

**Comment by alex-brinkman** [comment]
Resolved with `jsd/v1.5.1`
