### ISSUE TITLE
CMake Error at CMakeLists.txt:59 (FetchContent_MakeAvailable)

### ISSUE THREAD

**Issue by Mather10** [nasa-jpl/fastcat#26]
How to fix the error below

```
CMake Error at CMakeLists.txt:59 (FetchContent_MakeAvailable):
  Unknown CMake command "FetchContent_MakeAvailable".


-- Configuring incomplete, errors occurred!
See also "/content/build/build/build/fastcat/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
```

when running "cmake .."? Thanks.

**Comment by alex-brinkman** [comment]
`FetchContent` should be added as of Cmake v3.11 [source](https://cmake.org/cmake/help/latest/module/FetchContent.html)

The dependency should be properly check by this line `cmake_minimum_required (VERSION 3.11)` at the root CMakeLists.txt

Mind providing your cmake version (e.g. `cmake --version`) and any other system information so I can help (e.g. `uname -a`)

**Comment by alex-brinkman** [comment]
Feel free to reopen if this issue represents
