### ISSUE TITLE
Separation of reset command

### ISSUE THREAD

**Issue by davidinkyu-kim** [nasa-jpl/fastcat#6]
Currently when fastcat is resetted via reset command, the manager resets both jsd device and fastcat device.
In case of overriden function for egd drives, reset in egd_process invoke JSD_EGD_MODE_OF_OPERATION_PROF_POS.
This caused open brake situation where actuators try to catch up current pose even under heavy load. This could expose a problem of sagging if resetting opens all brakes.

Recommendation is to separate reset into
1) Reset: clears all latched fault status
2) Enable: Re-initialize device to be operational.

**Comment by alex-brinkman** [comment]
I have a branch that modifies the behavior of the `Reset` command to no longer disengage brakes. Before merging this into master, I'd like to test it out on an actuator with brakes. The "playground" hardware I have on had does not have a break.

**Comment by alex-brinkman** [comment]
https://github.com/nasa-jpl/fastcat/tree/abrinkma-actuator-reset-modification
