### ISSUE TITLE
Actuator commanded velocity clearance after a fault

### ISSUE THREAD

**Issue by davidinkyu-kim** [nasa-jpl/fastcat#72]
* Issue
  * After an actuator faults, `cmd_velocity` on the motor controller remains last commanded velocity and does not get resetted from Reset() command. Therefore, any consequent profiled command would generate a profile starting from residual commanded velocity, causing an actuator to move in undesired way
* Suggested solution
  * Generate a profile with initial velocity of "actual velocity"

**Comment by alex-brinkman** [comment]
I recommend the solution where we se the commanded pos/vel/current values to zero upon a fault.

**Comment by davidinkyu-kim** [comment]
Agreed, will be handled here: https://github.com/nasa-jpl/fastcat/pull/73
