### ISSUE TITLE
Message printing issue with brake disengage

### ISSUE THREAD

**Issue by d-loret** [nasa-jpl/fastcat#75]
I think we should remove the print statements when the servo is actually enabled and we don't wait for the brake to disengage (e.g. [here](https://github.com/nasa-jpl/fastcat/blob/master/src/jsd/actuator_fsm_helpers.cc#L282)). Strictly speaking, it brakes the real-time guarantee. In practice, it makes it difficult to look at Fastcat's output when the profile commands are used periodically, such as in EELS.

**Comment by JosephBowkett** [comment]
Closed with https://github.com/nasa-jpl/fastcat/pull/74
