### ISSUE TITLE
Is fastcat intended for flight?

### ISSUE THREAD

**Issue by mcevoyandy** [nasa-jpl/fastcat#99]
Maybe I missed this reading through the documentation, but is `fastcat` being built with the intention of using it for flight? If so, what's the target data and class of the software?

**Comment by alex-brinkman** [comment]
Fastcat is a EtherCAT device control framework mainly deployed to support robotics research and testbed applications. If you wanted to use if for any embedded application including flight, I would avoid `fastcat` which is designed to be highly flexible and uses STL containers and instead consider using `jsd` which is simpler, safer, but less flexible.
